
export const userConstant = {

    REGISTRATION_SUCCESS : "REGISTRATION_SUCCESS",
    REGISTRATION_FAILED : "REGISTRATION_FAILED",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILED : "LOGIN_FAILED",

}

